//
// imsmd_rootv1p2p1Doc.cs
//
// This file was generated by XMLSPY 2004 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSPY Documentation for further details.
// http://www.altova.com/xmlspy
//


using System;

namespace imsmd_rootv1p2p1
{
	public class imsmd_rootv1p2p1Doc : Altova.Document
	{
		override protected void DeclareNamespaces(Altova.Node node)
		{
			DeclareNamespace(node, "", "http://www.imsglobal.org/xsd/imsmd_rootv1p2p1");
		}
	}
}
