//
// schemaType.cs.cs
//
// This file was generated by XMLSPY 2004 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSPY Documentation for further details.
// http://www.altova.com/xmlspy
//


using Altova.Types;

namespace imscp_v1p1
{

	public class schemaType : SchemaString
	{
		public schemaType(string newValue) : base(newValue)
		{
			Validate();
		}

		public void Validate()
		{
		}
	}
}
