//
// adlcp_rootv1p2Doc.cs
//
// This file was generated by XMLSPY 2004 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSPY Documentation for further details.
// http://www.altova.com/xmlspy
//


using System;

namespace adlcp_rootv1p2
{
	public class adlcp_rootv1p2Doc : Altova.Document
	{
		override protected void DeclareNamespaces(Altova.Node node)
		{
			DeclareNamespace(node, "imscp", "http://www.imsproject.org/xsd/imscp_rootv1p1p2");
			DeclareNamespace(node, "", "http://www.adlnet.org/xsd/adlcp_rootv1p2");
		}
	}
}
