//
// newSchemaType.cs.cs
//
// This file was generated by XMLSPY 2004 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSPY Documentation for further details.
// http://www.altova.com/xmlspy
//


using Altova.Types;

namespace adlcp_rootv1p2
{

	public class newSchemaType : adlcp_rootv1p2.imscp.schemaType
	{
		public newSchemaType(string newValue) : base(newValue)
		{
			Validate();
		}

		new public void  Validate()
		{
			if (Value.Length > GetMaxLength())
				throw new System.Exception("Too long");
		}
		new public int GetMaxLength()
		{
			return 100;
		}
	}
}
