<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <UserSecretsId>aspnet-OpenSourceSCORMLMS-216CDD04-809C-4E90-8838-B15D3F9DACB5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="appsettings.Production..json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Karambolo.Extensions.Logging.File" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.0" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Identity\Services\" />
    <Folder Include="Data\Migrations\" />
    <Folder Include="SCORMPackages\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SCORM_XMLObjects\V1_2\adlcp_rootv1p2\adlcp_rootv1p2.csproj" />
    <ProjectReference Include="..\SCORM_XMLObjects\V1_2\Altova\Altova.csproj" />
    <ProjectReference Include="..\SCORM_XMLObjects\V1_2\imscp_rootv1p1p2\imscp_rootv1p1p2.csproj" />
    <ProjectReference Include="..\SCORM_XMLObjects\V1_2\imsmd_rootv1p2p1\imsmd_rootv1p2p1.csproj" />
    <ProjectReference Include="..\SCORM_XMLObjects\V1_3\adlcp_v1p3\adlcp_v1P3.csproj" />
  </ItemGroup>
</Project>
