//
// imscp_rootv1p1p2Doc.cs
//
// This file was generated by XMLSPY 2004 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSPY Documentation for further details.
// http://www.altova.com/xmlspy
//


using System;

namespace imscp_rootv1p1p2
{
	public class imscp_rootv1p1p2Doc : Altova.Document
	{
		override protected void DeclareNamespaces(Altova.Node node)
		{
			DeclareNamespace(node, "", "http://www.imsproject.org/xsd/imscp_rootv1p1p2");
		}
	}
}
