//
// measureType.cs.cs
//
// This file was generated by XMLSPY 2004 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSPY Documentation for further details.
// http://www.altova.com/xmlspy
//


using Altova.Types;

namespace imsss_v1p0
{

	public class measureType : SchemaDecimal
	{
		public measureType(string newValue) : base(newValue)
		{
			Validate();
		}

		public void Validate()
		{

			if (CompareTo(GetMaxInclusive()) > 0)
				throw new System.Exception("Out of range");

			if (CompareTo(GetMinInclusive()) < 0)
				throw new System.Exception("Out of range");
		}
		public SchemaDecimal GetMaxInclusive()
		{
			return new SchemaDecimal("1");
		}
		public SchemaDecimal GetMinInclusive()
		{
			return new SchemaDecimal("-1");
		}
	}
}
