//
// rollupConditionType.cs.cs
//
// This file was generated by XMLSPY 2004 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSPY Documentation for further details.
// http://www.altova.com/xmlspy
//


using System.Collections;
using System.Xml;

namespace imsss_v1p0
{
	public class rollupConditionType : Altova.Node
	{
		#region Forward constructors
		public rollupConditionType() : base() { SetCollectionParents(); }
		public rollupConditionType(XmlDocument doc) : base(doc) { SetCollectionParents(); }
		public rollupConditionType(XmlNode node) : base(node) { SetCollectionParents(); }
		public rollupConditionType(Altova.Node node) : base(node) { SetCollectionParents(); }
		#endregion // Forward constructors

		public override void AdjustPrefix()
		{
			int nCount;

			nCount = DomChildCount(NodeType.Attribute, "", "operator");
			for (int i = 0; i < nCount; i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Attribute, "", "operator", i);
				InternalAdjustPrefix(DOMNode, false);
			}

			nCount = DomChildCount(NodeType.Attribute, "", "condition");
			for (int i = 0; i < nCount; i++)
			{
				XmlNode DOMNode = GetDomChildAt(NodeType.Attribute, "", "condition", i);
				InternalAdjustPrefix(DOMNode, false);
			}
		}


		#region operator2 accessor methods
		public int Getoperator2MinCount()
		{
			return 0;
		}

		public int operator2MinCount
		{
			get
			{
				return 0;
			}
		}

		public int Getoperator2MaxCount()
		{
			return 1;
		}

		public int operator2MaxCount
		{
			get
			{
				return 1;
			}
		}

		public int Getoperator2Count()
		{
			return DomChildCount(NodeType.Attribute, "", "operator");
		}

		public int operator2Count
		{
			get
			{
				return DomChildCount(NodeType.Attribute, "", "operator");
			}
		}

		public bool Hasoperator2()
		{
			return HasDomChild(NodeType.Attribute, "", "operator");
		}

		public conditionOperatorType Getoperator2At(int index)
		{
			return new conditionOperatorType(GetDomNodeValue(GetDomChildAt(NodeType.Attribute, "", "operator", index)));
		}

		public conditionOperatorType Getoperator2()
		{
			return Getoperator2At(0);
		}

		public conditionOperatorType operator2
		{
			get
			{
				return Getoperator2At(0);
			}
		}

		public void Removeoperator2At(int index)
		{
			RemoveDomChildAt(NodeType.Attribute, "", "operator", index);
		}

		public void Removeoperator2()
		{
			while (Hasoperator2())
				Removeoperator2At(0);
		}

		public void Addoperator2(conditionOperatorType newValue)
		{
			AppendDomChild(NodeType.Attribute, "", "operator", newValue.ToString());
		}

		public void Insertoperator2At(conditionOperatorType newValue, int index)
		{
			InsertDomChildAt(NodeType.Attribute, "", "operator", index, newValue.ToString());
		}

		public void Replaceoperator2At(conditionOperatorType newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Attribute, "", "operator", index, newValue.ToString());
		}
		#endregion // operator2 accessor methods

		#region operator2 collection
        public operator2Collection	Myoperator2s = new operator2Collection( );

        public class operator2Collection: IEnumerable
        {
            rollupConditionType parent;
            public rollupConditionType Parent
			{
				set
				{
					parent = value;
				}
			}
			public operator2Enumerator GetEnumerator() 
			{
				return new operator2Enumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class operator2Enumerator: IEnumerator 
        {
			int nIndex;
			rollupConditionType parent;
			public operator2Enumerator(rollupConditionType par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.operator2Count );
			}
			public conditionOperatorType  Current 
			{
				get 
				{
					return(parent.Getoperator2At(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}
	
        #endregion // operator2 collection

		#region condition accessor methods
		public int GetconditionMinCount()
		{
			return 1;
		}

		public int conditionMinCount
		{
			get
			{
				return 1;
			}
		}

		public int GetconditionMaxCount()
		{
			return 1;
		}

		public int conditionMaxCount
		{
			get
			{
				return 1;
			}
		}

		public int GetconditionCount()
		{
			return DomChildCount(NodeType.Attribute, "", "condition");
		}

		public int conditionCount
		{
			get
			{
				return DomChildCount(NodeType.Attribute, "", "condition");
			}
		}

		public bool Hascondition()
		{
			return HasDomChild(NodeType.Attribute, "", "condition");
		}

		public rollupRuleConditionType GetconditionAt(int index)
		{
			return new rollupRuleConditionType(GetDomNodeValue(GetDomChildAt(NodeType.Attribute, "", "condition", index)));
		}

		public rollupRuleConditionType Getcondition()
		{
			return GetconditionAt(0);
		}

		public rollupRuleConditionType condition
		{
			get
			{
				return GetconditionAt(0);
			}
		}

		public void RemoveconditionAt(int index)
		{
			RemoveDomChildAt(NodeType.Attribute, "", "condition", index);
		}

		public void Removecondition()
		{
			while (Hascondition())
				RemoveconditionAt(0);
		}

		public void Addcondition(rollupRuleConditionType newValue)
		{
			AppendDomChild(NodeType.Attribute, "", "condition", newValue.ToString());
		}

		public void InsertconditionAt(rollupRuleConditionType newValue, int index)
		{
			InsertDomChildAt(NodeType.Attribute, "", "condition", index, newValue.ToString());
		}

		public void ReplaceconditionAt(rollupRuleConditionType newValue, int index)
		{
			ReplaceDomChildAt(NodeType.Attribute, "", "condition", index, newValue.ToString());
		}
		#endregion // condition accessor methods

		#region condition collection
        public conditionCollection	Myconditions = new conditionCollection( );

        public class conditionCollection: IEnumerable
        {
            rollupConditionType parent;
            public rollupConditionType Parent
			{
				set
				{
					parent = value;
				}
			}
			public conditionEnumerator GetEnumerator() 
			{
				return new conditionEnumerator(parent);
			}
		
			IEnumerator IEnumerable.GetEnumerator() 
			{
				return GetEnumerator();
			}
        }

        public class conditionEnumerator: IEnumerator 
        {
			int nIndex;
			rollupConditionType parent;
			public conditionEnumerator(rollupConditionType par) 
			{
				parent = par;
				nIndex = -1;
			}
			public void Reset() 
			{
				nIndex = -1;
			}
			public bool MoveNext() 
			{
				nIndex++;
				return(nIndex < parent.conditionCount );
			}
			public rollupRuleConditionType  Current 
			{
				get 
				{
					return(parent.GetconditionAt(nIndex));
				}
			}
			object IEnumerator.Current 
			{
				get 
				{
					return(Current);
				}
			}
    	}
	
        #endregion // condition collection

        private void SetCollectionParents()
        {
            Myoperator2s.Parent = this; 
            Myconditions.Parent = this; 
	}
}
}
