//
// hideLMSUIType.cs.cs
//
// This file was generated by XMLSPY 2004 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSPY Documentation for further details.
// http://www.altova.com/xmlspy
//


using Altova.Types;

namespace adlnav_v1p3
{

	public class hideLMSUIType : SchemaString
	{
		public hideLMSUIType(string newValue) : base(newValue)
		{
			Validate();
		}

		public void Validate()
		{
		}
	}
}
