//
// adlcp_v1p3Doc.cs
//
// This file was generated by XMLSPY 2004 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSPY Documentation for further details.
// http://www.altova.com/xmlspy
//


namespace adlcp_v1p3
{
	public class adlcp_v1p3Doc : Altova.Document
	{
		override protected void DeclareNamespaces(Altova.Node node)
		{
			DeclareNamespace(node, "", "http://www.adlnet.org/xsd/adlcp_v1p3");
		}
	}
}
